defaults: &defaults
    working_directory: ~/churros
    docker:
      - image: circleci/android:api-28-alpha
    resource_class: medium+
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Xmx3200m -Dorg.gradle.daemon=false

version: 2
jobs:
  build-test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew :app:testReleaseUnitTest --no-daemon --max-workers 4
          no_output_timeout: 5m

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-test
